#!/bin/bash
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
 ./nasm/bin/nasm -f elf32 $1.s && gcc -m32 -o $1 $1.o
else
 ./nasm/bin/nasm -f macho32 $1.s -o $1.o && ld -arch i386 -no_pie -lSystem -macosx_version_min 10.10 $1.o
fi
